#!/usr/bin/env python3
"""Add a "Related Breeds" section to breed + deep-dive pages (internal linking).

Computes breed similarity from each deep-dive's Quick Glance stats (primary
role, size with a distance penalty, activity, trainability), then adds a
styled chip section linking each breed to its 4 closest relatives. Injected
on both breeds/{slug}.html (links within breeds/) and deep-dives/{slug}.html
(links within deep-dives/), strengthening the site's internal link graph.

Idempotent: existing RELATED blocks (CSS + body, marked RELATED:BEGIN/END)
are replaced, not duplicated.
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).parent
N_RELATED = 4
SIZES = ["Small", "Medium", "Large", "Giant"]
SIZE_SCORE = {0: 3, 1: 1, 2: -2, 3: -4}

CSS_BEGIN = "    /* RELATED:BEGIN */"
CSS_END = "    /* RELATED:END */"
BODY_BEGIN = "  <!-- RELATED:BEGIN (generated by add_related.py) -->"
BODY_END = "  <!-- RELATED:END -->"

RELATED_CSS = "\n".join([
    CSS_BEGIN,
    "    .related-section { background: #FFF8EC; border: 2px solid #E0C090;",
    "      border-radius: 10px; padding: 22px 26px; box-shadow: 0 2px 8px rgba(92,61,17,0.12); }",
    "    .related-heading { font-size: 0.78rem; color: #7A4F2A; font-style: italic;",
    "      text-transform: uppercase; letter-spacing: 0.07em; margin-bottom: 14px; }",
    "    .related-links { display: flex; flex-wrap: wrap; gap: 10px; }",
    "    .related-links a { display: inline-block; background: #FAF0DC;",
    "      border: 1.5px solid #C05621; color: #C05621; text-decoration: none;",
    "      padding: 7px 14px; border-radius: 20px; font-size: 0.9rem;",
    "      transition: background 0.15s, color 0.15s; }",
    "    .related-links a:hover { background: #C05621; color: #FFF8EC; }",
    CSS_END,
])


def clean(s):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", s)).strip()


def load_breeds():
    breeds = {}
    for f in sorted((ROOT / "deep-dives").glob("*.html")):
        if f.name == "index.html":
            continue
        s = f.read_text(encoding="utf-8")
        name = clean(re.search(r"<h1[^>]*>(.*?)</h1>", s, re.S).group(1))
        st = {clean(l): clean(v) for l, v in re.findall(
            r'<div class="stat-label">(.*?)</div>\s*'
            r'<span class="stat-badge[^"]*">(.*?)</span>', s, re.S)}
        breeds[f.stem] = {"name": name, "st": st}
    return breeds


def similarity(a, b):
    A, B = a["st"], b["st"]
    score = 0
    ra = {x.strip() for x in A.get("Primary Role", "").split(",")}
    rb = {x.strip() for x in B.get("Primary Role", "").split(",")}
    score += 3 * len(ra & rb)
    sa, sb = A.get("Size"), B.get("Size")
    if sa in SIZES and sb in SIZES:
        score += SIZE_SCORE[abs(SIZES.index(sa) - SIZES.index(sb))]
    for k in ("Physical Activity Needs", "Trainability"):
        if A.get(k) and A.get(k) == B.get(k):
            score += 1
    return score


def related_for(slug, breeds):
    scored = [(similarity(breeds[slug], breeds[o]), o) for o in breeds if o != slug]
    scored.sort(key=lambda t: (-t[0], breeds[t[1]]["name"]))
    return [o for _, o in scored[:N_RELATED]]


def body_block(related, breeds):
    chips = "\n".join(
        f'      <a href="{o}.html">{html.escape(breeds[o]["name"])}</a>'
        for o in related)
    return (
        BODY_BEGIN + "\n"
        '  <section class="related-section">\n'
        '    <div class="related-heading">Related Breeds</div>\n'
        '    <div class="related-links">\n' + chips + "\n"
        "    </div>\n"
        "  </section>\n"
        + BODY_END
    )


def inject(path, related, breeds):
    src = path.read_text(encoding="utf-8")
    src = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END) + r"\n?",
                 "", src, flags=re.S)
    src = re.sub(re.escape(BODY_BEGIN) + r".*?" + re.escape(BODY_END) + r"\n?",
                 "", src, flags=re.S)

    src = src.replace("</style>", RELATED_CSS + "\n  </style>", 1)

    anchor = "\n</div>\n\n<footer"
    if anchor not in src:
        return False
    src = src.replace(anchor, "\n" + body_block(related, breeds) + "\n</div>\n\n<footer", 1)
    path.write_text(src, encoding="utf-8")
    return True


def main():
    breeds = load_breeds()
    done = 0
    for slug in breeds:
        rel = related_for(slug, breeds)
        for section in ("breeds", "deep-dives"):
            p = ROOT / section / f"{slug}.html"
            if p.exists() and inject(p, rel, breeds):
                done += 1
    print(f"Added Related Breeds to {done} pages ({len(breeds)} breeds x 2)")


if __name__ == "__main__":
    main()
