#!/usr/bin/env python3
"""Inject favicon <link> tags into every BarkFacts page (idempotent).

Adds a FAVICON:BEGIN/END block just before </head> on all pages,
referencing the icons generated by generate_favicon.py. Uses absolute
root paths (/favicon.ico ...) so the same markup works from the root,
breeds/ and deep-dives/ directories. Safe to re-run.
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
BEGIN = "  <!-- FAVICON:BEGIN (generated by add_favicon_links.py) -->"
END = "  <!-- FAVICON:END -->"

BLOCK = "\n".join([
    BEGIN,
    '  <link rel="icon" href="/favicon.ico" sizes="any" />',
    '  <link rel="icon" type="image/svg+xml" href="/favicon.svg" />',
    '  <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32.png" />',
    '  <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16.png" />',
    '  <link rel="apple-touch-icon" href="/apple-touch-icon.png" />',
    '  <link rel="manifest" href="/site.webmanifest" />',
    '  <meta name="theme-color" content="#5C3D11" />',
    END,
])


def discover():
    files = [ROOT / "index.html", ROOT / "about.html"]
    for section in ("breeds", "deep-dives"):
        files += sorted((ROOT / section).glob("*.html"))
    return [f for f in files if f.exists()]


def process(path: Path) -> bool:
    src = path.read_text(encoding="utf-8")
    src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                 "", src, flags=re.S)
    if "</head>" not in src:
        print(f"  ! no </head> in {path.name}")
        return False
    src = src.replace("</head>", BLOCK + "\n</head>", 1)
    path.write_text(src, encoding="utf-8")
    return True


def main():
    n = sum(process(f) for f in discover())
    print(f"Injected favicon links into {n} pages")


if __name__ == "__main__":
    main()
