#!/usr/bin/env python3
"""Add a "Sources & Further Reading" section to each deep-dive page (E-E-A-T).

Cites two REAL, HTTP-verified authoritative references per breed:
  1. the breed's official American Kennel Club page (per-breed; URLs verified
     and stored in akc_sources.txt), and
  2. VCA Animal Hospitals' veterinarian-reviewed dog health library.

No source is fabricated: URLs come from akc_sources.txt, which was built by
verify_akc.py checking live HTTP 200 responses. Idempotent (SOURCES:BEGIN/END
markers in <style> and body).
"""
import re
from pathlib import Path

ROOT = Path(__file__).parent
VCA_URL = "https://vcahospitals.com/know-your-pet"

CSS_BEGIN = "    /* SOURCES:BEGIN */"
CSS_END = "    /* SOURCES:END */"
BODY_BEGIN = "  <!-- SOURCES:BEGIN (generated by add_sources.py) -->"
BODY_END = "  <!-- SOURCES:END -->"

SOURCES_CSS = "\n".join([
    CSS_BEGIN,
    "    .sources-list { list-style: none; display: flex; flex-direction: column; gap: 9px; }",
    "    .sources-list li::before { content: '\\2192\\00a0'; color: #9A6B3A; }",
    "    .sources-list a { color: #C05621; text-decoration: none; font-size: 1rem; }",
    "    .sources-list a:hover { text-decoration: underline; }",
    "    .sources-note { margin-top: 14px; font-size: 0.82rem; font-style: italic; color: #7A4F2A; }",
    CSS_END,
])

AKC_NAME_SPECIAL = {
    "st-bernard": "St. Bernard",
    "poodle-standard": "Standard Poodle",
    "poodle-miniature": "Miniature Poodle",
    "poodle-toy": "Toy Poodle",
}


def akc_name(url):
    slug = url.rstrip("/").rsplit("/", 1)[-1]
    if slug in AKC_NAME_SPECIAL:
        return AKC_NAME_SPECIAL[slug]
    return " ".join(w.capitalize() for w in slug.split("-"))


def load_akc():
    m = {}
    for line in (ROOT / "akc_sources.txt").read_text(encoding="utf-8").splitlines():
        if "|" in line:
            slug, url = line.split("|", 1)
            m[slug.strip()] = url.strip()
    return m


def body_block(akc_url):
    return "\n".join([
        BODY_BEGIN,
        '  <section class="narrative-section sources-section">',
        '    <div class="narrative-heading">Sources &amp; Further Reading</div>',
        '    <ul class="sources-list">',
        f'      <li><a href="{akc_url}" target="_blank" rel="noopener">'
        f'{akc_name(akc_url)} at the American Kennel Club (AKC)</a></li>',
        f'      <li><a href="{VCA_URL}" target="_blank" rel="noopener">'
        f'Dog health library at VCA Animal Hospitals</a></li>',
        '    </ul>',
        '    <p class="sources-note">General references for further reading. '
        'For your own dog, always check with your veterinarian.</p>',
        '  </section>',
        BODY_END,
    ])


def process(path, akc_url):
    src = path.read_text(encoding="utf-8")
    src = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END) + r"\n?",
                 "", src, flags=re.S)
    src = re.sub(re.escape(BODY_BEGIN) + r".*?" + re.escape(BODY_END) + r"\n?",
                 "", src, flags=re.S)
    src = src.replace("</style>", SOURCES_CSS + "\n  </style>", 1)
    anchor = "\n</div>\n\n<footer"
    if anchor not in src:
        return False
    src = src.replace(anchor, "\n" + body_block(akc_url) + "\n</div>\n\n<footer", 1)
    path.write_text(src, encoding="utf-8")
    return True


def main():
    akc = load_akc()
    done = missing = 0
    for slug, url in akc.items():
        p = ROOT / "deep-dives" / f"{slug}.html"
        if not p.exists():
            missing += 1
            print(f"  ! no deep-dive for {slug}")
            continue
        if process(p, url):
            done += 1
    print(f"Added Sources to {done} deep-dive pages (missing: {missing})")


if __name__ == "__main__":
    main()
