#!/usr/bin/env python3
"""Inject SEO/AEO <head> tags into every BarkFacts page.

For each HTML page this adds, just before </head>, an idempotent block
(delimited by SEO:BEGIN / SEO:END markers) containing:
  - <meta name="description">
  - <link rel="canonical">
  - <meta name="robots">
  - Open Graph + Twitter Card tags
  - JSON-LD structured data (Article / CollectionPage / WebSite +
    BreadcrumbList), tuned per page type for search + AI answer engines.

Safe to re-run: an existing SEO block is replaced, not duplicated.
So it can be wired into the build_*.py generators too.
"""
import html
import json
import re
import subprocess
import datetime
from pathlib import Path

DOMAIN = "https://thebarkfacts.com"
SITE_NAME = "The Bark Facts"
ROOT = Path(__file__).parent

# Share image used for pages that have no single lead photo (home + indexes).
# Branded 1200x630 share card (generated by generate_og_image.py).
DEFAULT_OG_IMAGE = DOMAIN + "/images/og-cover.jpg"

BEGIN = "  <!-- SEO:BEGIN (generated by add_seo_meta.py — do not edit by hand) -->"
END = "  <!-- SEO:END -->"

ORG = {"@type": "Organization", "name": SITE_NAME, "url": DOMAIN + "/"}


# ---------- small helpers ----------

def text(raw: str) -> str:
    """Strip tags, unescape entities, collapse whitespace."""
    t = re.sub(r"<[^>]+>", " ", raw)
    return re.sub(r"\s+", " ", html.unescape(t)).strip()


def esc_attr(s: str) -> str:
    return (s.replace("&", "&amp;").replace('"', "&quot;")
             .replace("<", "&lt;").replace(">", "&gt;"))


def clip(s: str, n: int = 160) -> str:
    s = s.strip()
    if len(s) <= n:
        return s
    cut = s[: n - 1]
    if " " in cut:
        cut = cut[: cut.rfind(" ")]
    return cut.rstrip(" ,.;:—-") + "…"


def git_dates(path: Path):
    """(datePublished, dateModified) as YYYY-MM-DD from git; mtime fallback."""
    rel = str(path.relative_to(ROOT))
    def run(args):
        try:
            return subprocess.run(["git", *args, "--", rel], cwd=ROOT,
                                  capture_output=True, text=True,
                                  check=True).stdout.strip()
        except Exception:
            return ""
    modified = run(["log", "-1", "--format=%cs"])
    created = run(["log", "--diff-filter=A", "--format=%cs"]).splitlines()
    created = created[-1] if created else modified
    fallback = datetime.date.fromtimestamp(path.stat().st_mtime).isoformat()
    return (created or fallback, modified or fallback)


def first(pattern: str, s: str, default: str = "") -> str:
    m = re.search(pattern, s, re.I | re.S)
    return m.group(1).strip() if m else default


# ---------- per-page metadata ----------

def canonical(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return DOMAIN + "/"
    if rel.endswith("/index.html"):
        return DOMAIN + "/" + rel[: -len("index.html")]
    return DOMAIN + "/" + rel


def breed_name(body: str) -> str:
    return text(first(r"<h2[^>]*>(.*?)</h2>", body, "Dog"))


def breed_page_meta(path, body):
    name = breed_name(body)
    tagline = text(first(r'class="breed-tagline"[^>]*>(.*?)</p>', body))
    # Facts are pre-rendered into static .fact-text divs (see
    # render_facts_static.py); fall back to the legacy JS FACTS array.
    facts = [text(f) for f in
             re.findall(r'<div class="fact-text">(.*?)</div>', body, re.S)]
    if not facts:
        m = re.search(r"const FACTS\s*=\s*(\[.*?\]);", body, re.S)
        if m:
            try:
                facts = [text(f.get("fact", "")) for f in json.loads(m.group(1))]
            except Exception:
                facts = []
    photo = first(r'"file":\s*"([^"]+)"', body)
    image = DOMAIN + "/images/" + photo if photo else DEFAULT_OG_IMAGE
    desc = clip(f"{tagline} " + (facts[0] if facts else
                f"Quirky, true facts about the {name}."))
    created, modified = git_dates(path)
    ld = [
        {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": f"{name} Facts",
            "description": desc,
            "image": image,
            "author": ORG,
            "publisher": ORG,
            "datePublished": created,
            "dateModified": modified,
            "mainEntityOfPage": canonical(path),
            "about": {"@type": "Thing", "name": name},
            "articleBody": " ".join(facts),
            "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": DOMAIN + "/"},
        },
        breadcrumb([("Home", DOMAIN + "/"),
                    ("Dog Breeds", DOMAIN + "/breeds/"),
                    (name, canonical(path))]),
    ]
    return dict(title=f"{name} Facts", desc=desc, image=image,
                og_type="article", ld=ld)


def deep_dive_meta(path, body):
    name = breed_name(body)
    tagline = text(first(r'class="breed-tagline"[^>]*>(.*?)</p>', body))
    paras = [text(p) for p in re.findall(r"<p>(.*?)</p>", body, re.S)]
    paras = [p for p in paras if p]
    photo = first(r'class="narrative-img"[^>]*src="\.\./images/([^"]+)"', body)
    image = DOMAIN + "/images/" + photo if photo else DEFAULT_OG_IMAGE
    desc = clip(f"{tagline} " + (paras[0] if paras else
                f"An honest, in-depth look at the {name}."))
    created, modified = git_dates(path)
    ld = [
        {
            "@context": "https://schema.org",
            "@type": "Article",
            "headline": f"{name} — Deep Dive",
            "description": desc,
            "image": image,
            "author": ORG,
            "publisher": ORG,
            "datePublished": created,
            "dateModified": modified,
            "mainEntityOfPage": canonical(path),
            "about": {"@type": "Thing", "name": name},
            "articleBody": " ".join(paras),
            "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": DOMAIN + "/"},
        },
        breadcrumb([("Home", DOMAIN + "/"),
                    ("Deep Dives", DOMAIN + "/deep-dives/"),
                    (name, canonical(path))]),
    ]
    return dict(title=f"{name} — Deep Dive", desc=desc, image=image,
                og_type="article", ld=ld)


def breadcrumb(items):
    return {
        "@context": "https://schema.org",
        "@type": "BreadcrumbList",
        "itemListElement": [
            {"@type": "ListItem", "position": i + 1, "name": n, "item": u}
            for i, (n, u) in enumerate(items)
        ],
    }


def home_meta(path, body):
    desc = ("Quirky, true, and genuinely useful facts about dogs, one breed "
            "at a time. Browse breed facts and honest breed deep dives.")
    ld = [
        {"@context": "https://schema.org", "@type": "WebSite",
         "name": SITE_NAME, "url": DOMAIN + "/", "description": desc},
        {**{"@context": "https://schema.org"}, **ORG, "description": desc},
    ]
    return dict(title=SITE_NAME, desc=desc, image=DEFAULT_OG_IMAGE,
                og_type="website", ld=ld)


def breeds_index_meta(path, body):
    desc = ("Browse dog breeds and discover quirky, true facts about each one, "
            "from the Akita to the Whippet, one breed at a time.")
    ld = [
        {"@context": "https://schema.org", "@type": "CollectionPage",
         "name": "Dog Breeds", "description": desc, "url": canonical(path),
         "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": DOMAIN + "/"}},
        breadcrumb([("Home", DOMAIN + "/"), ("Dog Breeds", canonical(path))]),
    ]
    return dict(title=f"Dog Breeds — {SITE_NAME}", desc=desc,
                image=DEFAULT_OG_IMAGE, og_type="website", ld=ld)


def deep_index_meta(path, body):
    desc = ("Honest, in-depth deep dives on dog breeds: temperament, health, "
            "nutrition, family fit, and the real talk before you commit.")
    ld = [
        {"@context": "https://schema.org", "@type": "CollectionPage",
         "name": "Deep Dives", "description": desc, "url": canonical(path),
         "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": DOMAIN + "/"}},
        breadcrumb([("Home", DOMAIN + "/"), ("Deep Dives", canonical(path))]),
    ]
    return dict(title=f"Deep Dives — {SITE_NAME}", desc=desc,
                image=DEFAULT_OG_IMAGE, og_type="website", ld=ld)


def about_meta(path, body):
    desc = ("The story behind The Bark Facts: a lifelong dog lover who borrows "
            "everyone else's dogs, hands out treats at the park, and writes "
            "down the true, weird stuff about them.")
    ld = [
        {"@context": "https://schema.org", "@type": "AboutPage",
         "name": "About The Bark Facts", "description": desc,
         "url": canonical(path),
         "isPartOf": {"@type": "WebSite", "name": SITE_NAME, "url": DOMAIN + "/"}},
        breadcrumb([("Home", DOMAIN + "/"), ("About", canonical(path))]),
    ]
    return dict(title=f"About — {SITE_NAME}", desc=desc,
                image=DEFAULT_OG_IMAGE, og_type="website", ld=ld)


# ---------- assembly ----------

def build_block(path, meta):
    url = canonical(path)
    og = meta["og_type"]
    lines = [BEGIN,
             f'  <meta name="description" content="{esc_attr(meta["desc"])}" />',
             f'  <link rel="canonical" href="{url}" />',
             '  <meta name="robots" content="index, follow" />',
             f'  <meta property="og:site_name" content="{esc_attr(SITE_NAME)}" />',
             f'  <meta property="og:type" content="{og}" />',
             f'  <meta property="og:title" content="{esc_attr(meta["title"])}" />',
             f'  <meta property="og:description" content="{esc_attr(meta["desc"])}" />',
             f'  <meta property="og:url" content="{url}" />',
             f'  <meta property="og:image" content="{meta["image"]}" />',
             '  <meta name="twitter:card" content="summary_large_image" />',
             f'  <meta name="twitter:title" content="{esc_attr(meta["title"])}" />',
             f'  <meta name="twitter:description" content="{esc_attr(meta["desc"])}" />',
             f'  <meta name="twitter:image" content="{meta["image"]}" />']
    for obj in meta["ld"]:
        payload = json.dumps(obj, ensure_ascii=False, indent=2)
        payload = payload.replace("</", "<\\/")  # guard against </script>
        lines.append('  <script type="application/ld+json">')
        lines.append(payload)
        lines.append("  </script>")
    lines.append(END)
    return "\n".join(lines)


def route(path: Path):
    rel = path.relative_to(ROOT).as_posix()
    if rel == "index.html":
        return home_meta
    if rel == "about.html":
        return about_meta
    if rel == "breeds/index.html":
        return breeds_index_meta
    if rel == "deep-dives/index.html":
        return deep_index_meta
    if rel.startswith("breeds/"):
        return breed_page_meta
    if rel.startswith("deep-dives/"):
        return deep_dive_meta
    return None


def discover():
    files = [ROOT / "index.html", ROOT / "about.html"]
    for section in ("breeds", "deep-dives"):
        files += sorted((ROOT / section).glob("*.html"))
    return [f for f in files if f.exists()]


def process(path: Path) -> bool:
    src = path.read_text(encoding="utf-8")
    handler = route(path)
    if not handler:
        return False
    meta = handler(path, src)
    block = build_block(path, meta)

    # Remove any prior generated block (idempotent).
    src = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END) + r"\n?",
                 "", src, flags=re.S)
    if "</head>" not in src:
        print(f"  ! no </head> in {path.name}, skipped")
        return False
    src = src.replace("</head>", block + "\n</head>", 1)
    path.write_text(src, encoding="utf-8")
    return True


def main():
    n = 0
    for f in discover():
        if process(f):
            n += 1
    print(f"Injected SEO block into {n} pages")


if __name__ == "__main__":
    main()
