#!/usr/bin/env python3
"""Add an FAQ section + FAQPage schema to each deep-dive page (AEO).

Deep-dive pages carry the structured breed data (Quick Glance stats +
Health/Lifespan narrative). This generates 7 real, page-sourced Q&As per
breed, rendered as a visible FAQ section AND matching FAQPage JSON-LD, so
search + AI answer engines can surface them. The visible text and the schema
text are identical (required by Google's FAQ guidelines).

Idempotent: existing FAQ blocks (CSS + body, both marked FAQ:BEGIN/END) are
replaced, not duplicated.
"""
import html
import json
import re
from pathlib import Path

ROOT = Path(__file__).parent

CSS_BEGIN = "    /* FAQ:BEGIN */"
CSS_END = "    /* FAQ:END */"
BODY_BEGIN = "  <!-- FAQ:BEGIN (generated by add_faqs.py) -->"
BODY_END = "  <!-- FAQ:END -->"

FAQ_CSS = "\n".join([
    CSS_BEGIN,
    "    .faq-item { margin-bottom: 20px; }",
    "    .faq-item:last-child { margin-bottom: 0; }",
    "    .faq-q { font-size: 1.08rem; color: #5C3D11; margin-bottom: 5px; }",
    "    .faq-a { font-size: 1.02rem; line-height: 1.7; color: #3D2B1F; }",
    CSS_END,
])

SIZE = {"Small": "a small breed", "Medium": "a medium-sized breed",
        "Large": "a large breed", "Giant": "a giant breed"}
TRAIN = {
    "Easy": "The {b} is generally easy to train.",
    "Moderate": "The {b} is moderately trainable.",
    "Independent-Minded": "The {b} is independent-minded, which can make "
                          "training more challenging.",
}
BEGINNERS = {
    "Yes": "Yes — the {b} is generally considered a good fit for first-time "
           "dog owners.",
    "With Experience": "The {b} is best suited to owners who already have some "
                       "dog experience.",
    "Not Recommended": "The {b} is generally not recommended for first-time "
                       "owners.",
}
APARTMENT = {
    "Yes": "Yes — the {b} can adapt well to apartment living.",
    "With Enough Exercise": "The {b} can live in an apartment, as long as it "
                            "gets enough daily exercise.",
    "No": "The {b} is not well suited to apartment living and does better with "
          "more space.",
}


def clean(s):
    return re.sub(r"\s+", " ", html.unescape(re.sub(r"<[^>]+>", "", s))).strip()


def article(name):
    return "an" if name[:1].upper() in "AEIOU" else "a"


def build_faqs(name, stats, lifespan):
    b, art = name, article(name)
    faqs = []

    def add(q, a):
        if a:
            faqs.append((q, a))

    phys, mental = stats.get("Physical Activity Needs"), stats.get("Mental Stimulation Needs")
    if phys and mental:
        add(f"How much exercise does {art} {b} need?",
            f"The {b} has {phys.lower()} physical activity needs and "
            f"{mental.lower()} mental stimulation needs.")

    if stats.get("Size") in SIZE:
        add(f"What size is {art} {b}?", f"The {b} is {SIZE[stats['Size']]}.")

    if stats.get("Grooming Needs"):
        add(f"How much grooming does {art} {b} need?",
            f"The {b} has {stats['Grooming Needs'].lower()} grooming needs.")

    if stats.get("Trainability") in TRAIN:
        add(f"Is {art} {b} easy to train?", TRAIN[stats["Trainability"]].format(b=b))

    if stats.get("Good For Beginners") in BEGINNERS:
        add(f"Is the {b} a good choice for first-time owners?",
            BEGINNERS[stats["Good For Beginners"]].format(b=b))

    if stats.get("Apartment Friendly") in APARTMENT:
        add(f"Is {art} {b} apartment-friendly?",
            APARTMENT[stats["Apartment Friendly"]].format(b=b))

    if lifespan:
        add(f"How long does {art} {b} live?",
            f"The {b} typically lives {lifespan[0]}–{lifespan[1]} years.")

    return faqs


def visible_section(faqs):
    items = []
    for q, a in faqs:
        items.append(
            '    <div class="faq-item">\n'
            f'      <h3 class="faq-q">{html.escape(q)}</h3>\n'
            f'      <p class="faq-a">{html.escape(a)}</p>\n'
            '    </div>'
        )
    return (
        BODY_BEGIN + "\n"
        '  <section class="narrative-section faq-section">\n'
        '    <div class="narrative-heading">Frequently Asked Questions</div>\n'
        + "\n".join(items) + "\n"
        "  </section>\n"
        '  <script type="application/ld+json">\n'
        + faq_schema(faqs) + "\n"
        "  </script>\n"
        + BODY_END
    )


def faq_schema(faqs):
    obj = {
        "@context": "https://schema.org",
        "@type": "FAQPage",
        "mainEntity": [
            {"@type": "Question", "name": q,
             "acceptedAnswer": {"@type": "Answer", "text": a}}
            for q, a in faqs
        ],
    }
    return json.dumps(obj, ensure_ascii=False, indent=2).replace("</", "<\\/")


def process(path: Path):
    src = path.read_text(encoding="utf-8")

    name = clean(re.search(r"<h1[^>]*>(.*?)</h1>", src, re.S).group(1))
    stats = {clean(l): clean(v) for l, v in re.findall(
        r'<div class="stat-label">(.*?)</div>\s*'
        r'<span class="stat-badge[^"]*">(.*?)</span>', src, re.S)}
    m = re.search(r"(\d{1,2})\s*[–—\-]\s*(\d{1,2})\s*years", src, re.I)
    lifespan = (m.group(1), m.group(2)) if m else None

    faqs = build_faqs(name, stats, lifespan)
    if not faqs:
        return "skip (no data)"

    # Strip any prior FAQ blocks (idempotent).
    src = re.sub(re.escape(CSS_BEGIN) + r".*?" + re.escape(CSS_END) + r"\n?",
                 "", src, flags=re.S)
    src = re.sub(re.escape(BODY_BEGIN) + r".*?" + re.escape(BODY_END) + r"\n?",
                 "", src, flags=re.S)

    # Insert CSS before </style>.
    src = src.replace("</style>", FAQ_CSS + "\n  </style>", 1)

    # Insert the visible section + schema just inside the closing .main </div>.
    anchor = "\n</div>\n\n<footer"
    if anchor not in src:
        return "WARN: main/footer anchor not found — skipped"
    src = src.replace(anchor, "\n" + visible_section(faqs) + "\n</div>\n\n<footer", 1)

    path.write_text(src, encoding="utf-8")
    return f"{len(faqs)} FAQs"


def main():
    counts = {}
    for f in sorted((ROOT / "deep-dives").glob("*.html")):
        if f.name == "index.html":
            continue
        r = process(f)
        key = "added" if r.endswith("FAQs") else r
        counts[key] = counts.get(key, 0) + 1
        if r.startswith("WARN"):
            print(f"  {f.name}: {r}")
    for k, v in sorted(counts.items()):
        print(f"{k}: {v}")


if __name__ == "__main__":
    main()
