import json

new_facts_raw = [
    # History / Mythology
    ("History",  "Dogs were domesticated from gray wolves between 20,000 and 32,000 years ago, making them the first domesticated animal.", None),
    ("History",  "The oldest known dog burial dates to roughly 12,000 BCE — an elderly human was found interred with a puppy at Ein Mallaha, Israel.", None),
    ("History",  "Ancient Egyptians considered dogs so sacred that when a family dog died, the owners would shave their eyebrows as a sign of mourning.", None),
    ("History",  "Cerberus, the three-headed dog of Greek mythology, guarded the gates of the underworld and prevented the dead from escaping.", None),
    ("History",  "Anubis, the Egyptian god of the afterlife, was depicted as a man with the head of a dog and was believed to weigh the souls of the dead.", None),
    ("History",  "In 456 BC, a dog named Soter saved the city of Corinth by alerting citizens to an incoming Persian attack — 49 of the 50 guard dogs were killed in the battle.", None),
    ("History",  "The Saluki is depicted in ancient Egyptian art as far back as 2100 BCE, making it one of the oldest identifiable dog breeds in history.", "saluki"),
    ("History",  "The word 'canine' comes from the Latin 'canis,' meaning dog.", None),
    ("History",  "Dogs were the first animals ever domesticated by humans, predating cattle, sheep, and pigs by thousands of years.", None),
    ("History",  "In ancient Rome, 'Cave Canem' — meaning 'Beware of Dog' — signs were placed at house entrances. A famous mosaic example was found preserved at Pompeii.", None),
    ("History",  "The Dandie Dinmont Terrier is the only dog breed named after a fictional character — a farmer in Sir Walter Scott's 1815 novel 'Guy Mannering.'", None),
    ("History",  "Dogs served as messengers in World War I, carrying dispatches through enemy fire when radio communication failed.", None),
    ("History",  "During World War II, a 4-pound Yorkshire Terrier named Smoky served 12 combat missions and was awarded 8 battle stars.", None),
    ("History",  "Rin Tin Tin, a German Shepherd rescued from a WWI battlefield, starred in 27 Hollywood films and is credited with saving Warner Bros. from bankruptcy.", "german shepherd"),
    ("History",  "Laika, a Soviet stray dog, became the first animal to orbit Earth aboard Sputnik 2 in November 1957.", None),
    # Anatomy
    ("Anatomy",  "Dogs have 42 permanent teeth as adults, compared to humans' 32.", None),
    ("Anatomy",  "A dog's heart beats between 60 and 140 times per minute — smaller dogs have faster resting heart rates than larger ones.", None),
    ("Anatomy",  "Dogs have approximately 1,700 taste buds, compared to humans' roughly 9,000, which is why they are far less picky about flavor than we are.", None),
    ("Anatomy",  "A dog's normal body temperature ranges from 101 to 102.5°F (38.3–39.2°C) — higher than a human's 98.6°F.", None),
    ("Anatomy",  "Dogs have 18 muscles in each ear, allowing them to rotate and tilt each ear independently to pinpoint sounds.", None),
    ("Anatomy",  "A dog's whiskers — called vibrissae — are deeply rooted touch-sensitive hairs that detect subtle changes in air currents.", None),
    ("Anatomy",  "Dogs sweat primarily through their paw pads, not through the skin the way humans do.", None),
    ("Anatomy",  "Dogs have a third eyelid called the nictitating membrane that sweeps across the eye to keep it moist and protected.", None),
    ("Anatomy",  "A dog's field of vision spans roughly 250 degrees, compared to a human's 180 degrees — giving them a much wider view of their surroundings.", None),
    ("Anatomy",  "Dogs have approximately 50 vertebrae — considerably more than a human's 33 — giving their spines more flexibility.", None),
    ("Anatomy",  "Every dog's nose print is unique, like a human fingerprint — some kennel clubs and registries accept nose prints as a form of identification.", None),
    ("Anatomy",  "A dog's nose secretes a thin layer of mucus that helps absorb scent chemicals, which the dog then licks off to further analyze with taste receptors.", None),
    ("Anatomy",  "A dog's paw pads contain sweat glands — this is why dogs sometimes leave damp footprints on smooth floors during hot weather.", None),
    # Biology
    ("Biology",  "A dog's nose contains up to 300 million scent receptors, compared to about 5 million in the human nose.", None),
    ("Biology",  "The area of a dog's brain devoted to analyzing scent is proportionally 40 times larger than the equivalent area in the human brain.", None),
    ("Biology",  "Dogs can hear sounds four times farther away than humans can, and can detect frequencies up to 65,000 Hz.", None),
    ("Biology",  "The fastest recorded dog speed belongs to a Greyhound clocked at 45 mph (72 km/h), making it the fastest land animal over short distances after the cheetah.", "greyhound"),
    ("Biology",  "Dogs can get sunburned — particularly on their nose, ear tips, and belly — if exposed to intense sunlight for extended periods.", None),
    ("Biology",  "Puppies are born blind, deaf, and without teeth. Their eyes and ear canals open between 10 and 14 days after birth.", None),
    ("Biology",  "Large breeds age faster and have shorter lifespans than small breeds — a Great Dane may live only 7–8 years while a Chihuahua can reach 15–17 years.", None),
    ("Biology",  "Dogs have a specialized organ in their nose called the Jacobson's organ — also known as the vomeronasal organ — that detects pheromones.", None),
    ("Biology",  "Female dogs can experience false pregnancies, displaying physical and behavioral signs of pregnancy — including nesting and milk production — without actually being pregnant.", None),
    ("Biology",  "Dogs are susceptible to many of the same diseases as humans, including diabetes, cancer, epilepsy, and heart disease, making them valuable models in medical research.", None),
    ("Biology",  "The dog genome was fully sequenced in 2005, using DNA from a Boxer named Tasha — it was a landmark in both veterinary and human medicine.", "boxer"),
    # Sensory
    ("Sensory",  "Dogs can detect certain types of cancer through smell alone, with trained dogs achieving over 90% accuracy in some clinical studies.", None),
    ("Sensory",  "Some dogs can predict epileptic seizures minutes before they occur, giving their owners time to get to safety.", None),
    ("Sensory",  "Dogs can sense changes in atmospheric pressure and static electricity — which is why many seem anxious before thunderstorms.", None),
    ("Sensory",  "A dog's nose is so sensitive it can detect the equivalent of a teaspoon of sugar dissolved in a million gallons of water.", None),
    ("Sensory",  "Dogs can distinguish the smell of identical twins even when the twins share the same home and diet.", None),
    ("Sensory",  "Dogs see the world primarily in shades of blue and yellow and cannot distinguish red from green — similar to human red-green colorblindness.", None),
    ("Sensory",  "A dog can locate the exact source of a sound in 1/600th of a second by independently adjusting each ear.", None),
    ("Sensory",  "Dogs have been trained to detect COVID-19 through scent with up to 94% accuracy, according to studies conducted during the pandemic.", None),
    ("Sensory",  "Some dogs can detect dangerously low blood sugar in diabetic owners before the owner themselves notices any symptoms.", None),
    ("Sensory",  "Dogs can detect human emotions through smell — they can literally smell fear, stress, and even happiness through subtle chemical changes in human sweat.", None),
    ("Sensory",  "Dogs have been trained to sniff out malaria in children from the scent of their socks with approximately 70% accuracy.", None),
    ("Sensory",  "Sniffer dogs at airports can detect over 50 types of controlled substances, various explosives, and even contraband electronics.", None),
    ("Sensory",  "Greyhounds have a nearly 270-degree field of vision — wider than almost any other dog breed — designed for tracking fast-moving prey across open terrain.", "greyhound"),
    # Behavior
    ("Behavior", "Dogs dream during REM sleep — often twitching, paddling their legs, or whimpering — and are believed to replay the events of their day.", None),
    ("Behavior", "Puppies can sleep up to 20 hours a day; adult dogs typically sleep 12 to 14 hours, far more than humans.", None),
    ("Behavior", "Dogs are one of the few non-human animals shown to display voluntary, unselfish kindness toward others without expecting any reward.", None),
    ("Behavior", "When a dog wags its tail to the right, it typically signals positive emotions; a left-leaning wag can indicate anxiety or uncertainty.", None),
    ("Behavior", "Dogs are naturally pack animals and instinctively look to their human family as their social group, seeking structure and companionship.", None),
    ("Behavior", "A dog yawning in your presence is not always tiredness — it can be a 'calming signal' used to communicate peaceful intentions.", None),
    ("Behavior", "Dogs curl into a ball while sleeping as an instinct to protect vital organs from predators — a behavior retained from their wild wolf ancestors.", None),
    ("Behavior", "Dogs have a 'guilty look,' but research suggests this expression is a response to a human's tone and body language rather than actual guilt.", None),
    ("Behavior", "Dogs can be left-pawed or right-pawed, and roughly 50% favor their right paw — studies suggest this may correlate with differences in personality.", None),
    ("Behavior", "Male dogs typically lift their leg to urinate against vertical surfaces to make their scent appear to come from a larger, taller dog.", None),
    ("Behavior", "Dogs mark territory not just with urine but also through scent glands located in their cheeks, paws, and the base of their tail.", None),
    ("Behavior", "Dogs have been shown to yawn contagiously in response to a human yawn — especially when the yawning human is someone they know and trust.", None),
    ("Behavior", "Dogs have a rudimentary sense of time and can estimate how long their owner has been away — possibly by detecting the fading strength of their scent.", None),
    ("Behavior", "Service dogs can be trained to turn on light switches, open doors, retrieve dropped objects, and dial specially adapted emergency phones.", None),
    # Intelligence
    ("Intelligence", "The average dog can learn around 165 words and gestures, with highly trained dogs learning 250 or more.", None),
    ("Intelligence", "Dogs are capable of basic counting — they can tell that one object plus one object equals two, and notice when an arithmetic result seems wrong.", None),
    ("Intelligence", "Dogs follow human pointing gestures better than any other animal — including chimpanzees — and can do so without any training.", None),
    ("Intelligence", "Dogs learn fastest through positive reinforcement. Rewarding desired behavior consistently produces faster, more reliable results than punishment.", None),
    ("Intelligence", "Dogs have episodic memory — they can recall specific past events and experiences, not just trained responses.", None),
    ("Intelligence", "Dogs can recognize their owner's car by the sound of the engine from a distance, even among many vehicles with similar sounds.", None),
    ("Intelligence", "A Border Collie named Chaser learned the individual names of over 1,022 separate objects — the largest tested vocabulary of any non-human animal.", "border collie"),
    ("Intelligence", "Border Collies are widely considered the most intelligent dog breed — they can learn a new command in under five seconds and obey it 95% of the time.", "border collie"),
    ("Intelligence", "Dogs can read human facial expressions, preferring to look at happy faces, and can distinguish between positive and negative emotional states.", None),
    ("Intelligence", "Dogs have been shown to understand the concept of fairness: they become visibly upset if another dog receives a better reward for performing the same task.", None),
    ("Intelligence", "A dog named Rico demonstrated 'fast mapping' in 2009 — the same word-learning shortcut used by human children — to rapidly associate names with new objects.", None),
    ("Intelligence", "Dogs can recognize their owner's voice on a recording and show a measurably stronger response to it than to a stranger's voice.", None),
    ("Intelligence", "The dog is the only animal known to have a natural, untrained ability to understand human communicative intent — including pointing, gaze, and tone of voice.", None),
    ("Intelligence", "Dogs possess a form of 'theory of mind' — they can track what another individual knows or has seen and adjust their behavior accordingly.", None),
    # Health & Wellbeing
    ("Health",   "Petting a dog for just 15 minutes triggers the release of oxytocin, serotonin, and prolactin in the human brain — the same hormones involved in social bonding.", None),
    ("Health",   "When you gaze into your dog's eyes, both your and your dog's oxytocin levels rise — the same bonding mechanism found between human parents and their infants.", None),
    ("Health",   "Therapy dogs have been shown to lower blood pressure, reduce cortisol levels, and speed recovery from surgery in hospital patients.", None),
    ("Health",   "Dogs have been found to significantly reduce feelings of loneliness and depression — their presence alone lowers cortisol (the stress hormone) in humans.", None),
    ("Health",   "Dogs can develop Canine Cognitive Dysfunction (CCD) — an Alzheimer's-like condition that affects up to 28% of dogs aged 11–12 and 68% of dogs aged 15–16.", None),
    ("Health",   "Dogs' mouths are not cleaner than humans' mouths — this is a common myth. They simply harbor different bacteria, most of which don't affect humans.", None),
    ("Health",   "Obese dogs live on average 1.5 fewer years than dogs at a healthy weight, according to long-term studies of dog lifespan and body condition.", None),
    ("Health",   "Dogs age more rapidly in their early years — by age 1, a dog is biologically equivalent to a 30-year-old human in terms of cellular aging markers.", None),
    # Records
    ("Records",  "The world's oldest dog on record was an Australian Cattle Dog named Bluey, who lived to 29 years and 5 months — nearly double the average canine lifespan.", None),
    ("Records",  "The tallest dog ever recorded was a Great Dane named Zeus, who stood 44 inches (112 cm) at the shoulder and could look over a countertop while standing on all fours.", "great dane"),
    ("Records",  "The smallest dog ever recorded was a Chihuahua named Miracle Milly, who measured just 3.8 inches (9.65 cm) tall and weighed under a pound.", "chihuahua"),
    ("Records",  "The highest jump by a dog is 75.5 inches (191.7 cm), set by a Greyhound mix named Feather in Frederick, Maryland in 2017.", "greyhound"),
    ("Records",  "A Labrador Retriever named Endal could operate an ATM, shop in stores, and summon help in emergencies — widely considered the most decorated service dog in history.", None),
    # Breeds — specific facts
    ("Breeds",   "The Australian Shepherd was developed in the western United States, not Australia — it was bred by Basque shepherds who had passed through Australia before emigrating to America.", "australian shepherd"),
    ("Breeds",   "The Poodle's distinctive haircut was originally designed to improve its swimming ability as a waterfowl retriever — pompoms were left to protect the joints from cold water.", "poodle"),
    ("Breeds",   "Dalmatian puppies are born completely white — their distinctive spots begin to appear within the first three to four weeks of life.", "dalmatian"),
    ("Breeds",   "The Basenji is the only domestic dog that cannot bark. Instead of barking, it produces a distinctive yodeling sound known as a 'barroo.'", "basenji"),
    ("Breeds",   "The Norwegian Lundehund has six fully functional toes on each foot and can bend its head all the way back to touch its spine — adaptations developed for puffin hunting on steep cliffs.", None),
    ("Breeds",   "The Chow Chow is among the oldest dog breeds, with fossils resembling the breed found in China dating back more than 2,000 years.", "chow chow"),
    ("Breeds",   "The Irish Wolfhound is the tallest dog breed by average height — when standing on its hind legs, it can reach over 7 feet tall.", "irish wolfhound"),
    ("Breeds",   "The Dachshund was originally bred to hunt badgers — its name literally translates to 'badger dog' in German, and its long body was perfect for following prey into burrows.", "dachshund"),
    ("Breeds",   "The Labrador Retriever was the most popular dog breed in the United States for more than 30 consecutive years before recently being overtaken by the French Bulldog.", None),
    ("Breeds",   "The St. Bernard was developed by monks at the Great St. Bernard Hospice in the Swiss Alps specifically to rescue travelers stranded in avalanches.", "saint bernard"),
    ("Breeds",   "The Siberian Husky can run up to 100 miles a day at sustained speeds of 10–15 mph, burning far fewer calories per mile than scientists initially predicted.", "siberian husky"),
    ("Breeds",   "The Alaskan Malamute is the official state dog of Alaska, recognized for its historical role in sled transport and its deep ties to indigenous Alaskan culture.", "alaskan malamute"),
    ("Breeds",   "The Great Dane was once known as the 'Deutsche Dogge' and was the official dog of Germany, bred to hunt wild boar alongside German nobility.", "great dane"),
    ("Breeds",   "Pugs were bred as lap dogs for Chinese emperors during the Han dynasty and were kept in luxury accommodations with soldiers assigned to guard them.", "pug"),
    ("Breeds",   "Bulldogs were originally bred for bull-baiting, a sport banned in England in 1835 — after the ban, breeders selectively developed the gentle, affectionate temperament Bulldogs are known for today.", "bulldog"),
    ("Breeds",   "The Boxer breed gets its name from its distinctive habit of standing on its hind legs and sparring with its front paws — a behavior seen during play.", "boxer"),
    ("Breeds",   "The Weimaraner was developed in early 19th-century Germany for hunting large game such as deer, boar, and bear — it was originally called the 'Weimar Pointer.'", "weimaraner"),
    ("Breeds",   "The Vizsla is the only breed that is uniformly golden-rust in color — its nose, eyes, nails, and coat all match, making it one of the most visually consistent breeds.", "vizsla"),
    ("Breeds",   "The Borzoi can reportedly see objects nearly a mile away, thanks to its wide-angle vision and deep chest that supports long, sustained running in open terrain.", "borzoi"),
    ("Breeds",   "The Pembroke Welsh Corgi is one of the breeds most closely associated with British royalty — Queen Elizabeth II owned more than 30 Corgis over the course of her reign.", "corgi"),
    ("Breeds",   "The Beagle's white-tipped tail was selectively bred so hunters could spot the dog in tall grass during a hunt, even when the rest of its body was hidden.", "beagle"),
    ("Breeds",   "The Dalmatian's strong association with firehouses dates back to the era of horse-drawn fire carriages — Dalmatians ran alongside to clear paths and calm the horses.", "dalmatian"),
    ("Breeds",   "The Rottweiler descended from the Roman Molossus, a massive war dog that accompanied Roman legions through Europe to herd cattle and guard camps.", "rottweiler"),
    ("Breeds",   "The German Shepherd breed was formally established in 1899 by cavalry captain Max von Stephanitz, who sought to create the ultimate working dog.", "german shepherd"),
    ("Breeds",   "The Doberman Pinscher was created in the 1880s by a German tax collector named Karl Friedrich Louis Dobermann, who wanted a loyal and intimidating companion for his rounds.", "doberman"),
    ("Breeds",   "The Samoyed's permanently upturned mouth corners — the famous 'Samoyed smile' — prevent drooling in freezing temperatures, which could cause ice to form on the dog's face.", "samoyed"),
    ("Breeds",   "The Shiba Inu was nearly wiped out during World War II. Only three surviving breeding lines were combined after the war to restore the breed.", "shiba inu"),
    ("Breeds",   "The Akita is considered a symbol of good health and happiness in Japan. Small Akita figurines are traditionally given to sick patients as a wish for swift recovery.", "akita"),
    ("Breeds",   "Jack Russell Terriers were bred by Reverend John Russell in the 1800s specifically to bolt foxes from their dens during hunts without injuring them.", "jack russell terrier"),
    ("Breeds",   "The Pointer's signature 'point' — freezing with nose, body, and raised paw aimed directly at game — is an instinctive behavior nearly unique in the animal kingdom.", "pointer"),
    ("Breeds",   "The Pembroke and Cardigan Welsh Corgis are two entirely separate breeds. The Cardigan is the older of the two and has a long tail; the Pembroke typically does not.", "corgi"),
    ("Breeds",   "The Finnish Lapphund was used by the Sámi people of northern Scandinavia for thousands of years to herd reindeer across the Arctic tundra.", "finnish lapphund"),
    ("Breeds",   "The Papillon gets its name from the French word for 'butterfly,' referring to the shape of its large, fringed, wing-like ears.", "papillon"),
    ("Breeds",   "The Bull Terrier is the only dog breed with distinctly triangular eyes — it is the only breed in the world with non-oval eyes.", "bull terrier"),
    ("Breeds",   "The Basset Hound's long, velvety ears serve a functional purpose: they sweep scent particles from the ground upward toward the nose while the dog tracks a trail.", "basset hound"),
    ("Breeds",   "The Great Pyrenees has double dewclaws — two extra toes — on each hind foot, an evolutionary adaptation that provides better grip on snowy mountain terrain.", "great pyrenees"),
    ("Breeds",   "The Portuguese Water Dog has webbed feet, a waterproof coat, and a thick tail used as a rudder — all natural adaptations for herding fish and retrieving gear at sea.", "portuguese water dog"),
    # History — famous dogs & culture
    ("History",  "A dog named Hachiko, an Akita, waited loyally at Shibuya Station in Tokyo every day for nine years after his owner died in 1925. A bronze statue of Hachiko stands at the station today.", "akita"),
    ("History",  "A Newfoundland named Seaman accompanied Meriwether Lewis on the Lewis and Clark Expedition of 1804–1806, trekking thousands of miles across North America.", "newfoundland"),
    ("History",  "Barry, a legendary St. Bernard rescue dog who worked in the Swiss Alps in the early 1800s, is credited with saving more than 40 lives.", "saint bernard"),
    ("History",  "The Shiba Inu is one of Japan's six native breeds and has been designated a Natural Monument of Japan, protected by the government since 1936.", "shiba inu"),
    ("History",  "In Aztec culture, the Xoloitzcuintli — the Mexican Hairless Dog — was believed to guide the souls of the deceased safely through the underworld after death.", None),
    ("History",  "Dogs were used by the ancient Egyptians as hunting companions over 4,000 years ago, with depictions of sighthound-type dogs appearing in tomb paintings across the Nile Valley.", None),
    ("History",  "The Pomeranian was originally a much larger sled-pulling dog from the Pomerania region of Europe — Queen Victoria is credited with popularizing the miniature version after returning from a trip to Florence in 1888.", None),
    ("History",  "Dogs and wolves living today both descend from an ancient wolf population that lived alongside woolly mammoths, according to genetic studies published in 2022.", None),
    ("History",  "Belka and Strelka became the first dogs to survive orbital spaceflight, returning safely to Earth after a day in space on August 20, 1960.", None),
    ("History",  "Paul McCartney recorded a high-frequency whistle at the end of the Beatles song 'A Day in the Life' specifically so that only dogs could hear it.", None),
    ("History",  "The term 'dog days of summer' comes from Roman astronomy — the sweltering heat was believed to occur when Sirius, the Dog Star, rose alongside the sun.", None),
    ("History",  "Greyhounds are the only breed specifically mentioned in the Bible (Proverbs 30:31 in certain translations), described among things that are 'stately in their stride.'", "greyhound"),
    # Culture
    ("Culture",  "The United States has the highest dog population in the world, with an estimated 90 million pet dogs — roughly one dog for every four households.", None),
    ("Culture",  "The most popular dog names in the United States are 'Max' for males and 'Bella' for females, according to data collected from veterinary clinics and registries.", None),
    ("Culture",  "Police dogs — K9s — are often granted official officer rank in their departments. In many jurisdictions, harming a police dog is treated as assaulting a law enforcement officer.", None),
    ("Culture",  "Dogs are mentioned 35 times in the Bible, making them the most frequently referenced animal in that text.", None),
    ("Culture",  "In ancient China, Emperor Tang of the Tang dynasty reportedly owned 2,500 pairs of hunting dogs, each pair with a dedicated handler.", "chow chow"),
    ("Culture",  "In South Korea, it is considered good luck to have a dog cross your path — the opposite of the superstition many cultures hold about black cats.", None),
]

with open('E:/ClaudeCode/dog_facts/dog_facts.json', encoding='utf-8') as f:
    facts_data = json.load(f)

start_num = max(f['fact_number'] for f in facts_data['facts']) + 1

for i, (category, fact_text, breed) in enumerate(new_facts_raw):
    facts_data['facts'].append({
        'fact_number': start_num + i,
        'category': category,
        'fact': fact_text,
        'breed': breed,
    })

with open('E:/ClaudeCode/dog_facts/dog_facts.json', 'w', encoding='utf-8') as f:
    json.dump(facts_data, f, indent=2, ensure_ascii=False)

total = len(facts_data['facts'])
new_count = total - (start_num - 1)
tagged = sum(1 for f in facts_data['facts'][start_num-1:] if f['breed'])
print(f"Added {new_count} new facts (#{start_num}–#{start_num+new_count-1})")
print(f"{tagged} of the new facts have breed tags")
print(f"Total facts in file: {total}")
